In [5]:
from quippy.descriptors import Descriptor
from ase.io import read
import numpy as np

In [6]:
#mol = read("data.xyz@:",format="extxyz")
all_molecules = read("/datavon1/DatabasesMolecules/LiH/LiH.xyz@:",format="extxyz")

In [7]:
#Descriptor_description = f"soap cutoff=3 zeta=2 delta = 1.0 atom_sigma = 1.0 l_max=2 n_max=3 add_species=F"
Descriptor_description = f"soap cutoff=5.0 zeta=2 delta = 1.0 atom_sigma =1.0 l_max=8 n_max=10 n_Z=2 Z={{1 3}} n_species=2 species_Z={{1 3}}"
soap = Descriptor(Descriptor_description)
soaps = soap.calc(all_molecules, grad=True)

In [8]:
desc_soaps = []
for a in soaps:
    desc_soaps.extend(a["data"])
desc_soaps = np.array(desc_soaps)

In [9]:
# CUR decompostion from QUIP
import numpy as np
np.random.seed(10)
k = 10
epsilon = 0.45
c = k*(np.log(k))/(epsilon**2)

n_struc = len(desc_soaps)
trainT = np.transpose(desc_soaps)

u,s,V = np.linalg.svd(trainT)

In [ ]:
u,s,V = np.linalg.svd(trainT)
print(V.shape)
V = V[:k,:]
print(V.shape)
probV = 1/k*np.sum(V**2,axis=0)
print((probV))

(66, 66)
(10, 66)
[0.01132244 0.00631873 0.00540122 0.01197489 0.00737003 0.00519207
 0.01169453 0.00540704 0.00637812 0.02314218 0.01293746 0.01247448
 0.05389146 0.03593209 0.03593196 0.02314225 0.0129375  0.01247447
 0.01994297 0.00557422 0.01777782 0.01994296 0.01777784 0.00557423
 0.01994295 0.00557424 0.01777785 0.01994298 0.01777778 0.00557424
 0.01930968 0.00827416 0.03039849 0.00623203 0.00489082 0.02685884
 0.00622675 0.00549072 0.01656373 0.03156417 0.00844582 0.01761038
 0.00704648 0.00763723 0.00864527 0.03805104 0.00757054 0.00757054
 0.00704651 0.00763723 0.00864527 0.01846063 0.00940974 0.03328524
 0.01227209 0.00583702 0.0060588  0.00967913 0.00681209 0.00501641
 0.01573803 0.00451842 0.00463069 0.02198178 0.00678623 0.09069499]


In [ ]:
V = V[:k,:]
probV = 1/k*np.sum(V**2,axis=0)
print(np.argsort(probV))
repres = [soa

[61 62 34 59  5  2  7 37 19 23 25 29 55 56 36 33  1  8 64 58 42 48  4 47
 46 43 49 31 40 50 44 52 57  0  6  3 54 17 11 10 16 60 38 41 28 20 22 26
 51 30 24 21 18 27 63  9 15 35 32 39 53 14 13 45 12 65]


In [ ]:
C_vec = [np.random.choice(2, p=[1 - min(1, c * probV[strucN]), min(1, c * probV[strucN])],replace=False) for strucN in range(n_struc)]
picked = np.nonzero(C_vec)[0]
if self.multi_SOAP == False:
    self.representing_set_descriptors = [self.training_set_descriptors[pos] for pos in picked]
elif self.multi_SOAP == True:
    self.representing_set_descriptors = []
    for ind in range(len(self.training_set_descriptors)):
        self.representing_set_descriptors.append([self.training_set_descriptors[ind][pos] for pos in picked])
self.sparse = True
return picked

In [21]:
print(len(all_molecules[100]))
print(len(soaps[100]["grad_data"]))f
print(8*7)

8
60
56


In [ ]:
h=0.001
iatom = 0
direction=0
tmpmol = mol[0].copy()
pos = tmpmol.get_positions()
pos[iatom][direction] += h
tmpmol.set_positions(pos)
Kplus = soap.calc(tmpmol)['data']
pos[iatom][direction] += -2.0*h
tmpmol.set_positions(pos)
Kminus = soap.calc(tmpmol)['data']
pos[iatom][direction] += h
tmpmol.set_positions(pos)
print((Kplus-Kminus)/(2.0*h))

[[ 4.41703535e-01 -6.26006231e-03 -3.29416402e-03 -9.48082934e-01
  -6.66118164e-02 -3.50526975e-02 -4.15073714e-01 -3.54400153e-01
  -1.86495208e-01  8.65896544e-03  5.99977876e-04  3.12004897e-04
   5.35367836e-03  4.51432567e-03  2.34759314e-03 -3.45261951e-05
  -2.87489438e-05 -1.47662800e-05  0.00000000e+00]
 [-7.43935314e-02  9.27169760e-05  3.76215866e-04  7.70655815e-02
   9.86597668e-04  4.00309821e-03  7.27509315e-02  5.24917334e-03
   2.12973411e-02 -7.33653386e-04 -8.64826130e-06 -3.76434381e-05
  -9.70756380e-04 -6.50721509e-05 -2.83226173e-04  6.47648854e-06
   4.02619115e-07  1.88348629e-06  0.00000000e+00]
 [ 4.18480436e-02 -7.88349721e-04 -4.02641316e-04 -1.10547154e-01
  -8.38838560e-03 -4.28430868e-03 -3.85045866e-02 -4.46280445e-02
  -2.27936132e-02  1.05079315e-03  7.87995511e-05  3.98747298e-05
   5.12668941e-04  5.92881924e-04  3.00016469e-04 -3.41271259e-06
  -3.93825240e-06 -1.97492766e-06  0.00000000e+00]
 [ 1.59450909e-01 -2.47086760e-03 -1.43080635e-03 -3.34

In [ ]:
import numpy as np
a = np.array([2,10,2,3,9,5])
print(np.argsort(a))


[0 2 3 5 4 1]


In [ ]:
a1 = np.array([[1,2],[2,3]])
print(a1)
a2 = np.array([[10,20],[20,30]])
print(a2)
print(np.eye(2))
print(np.kron(np.eye(2),a1))

[[1 2]
 [2 3]]
[[10 20]
 [20 30]]
[[1. 0.]
 [0. 1.]]
[[1. 2. 0. 0.]
 [2. 3. 0. 0.]
 [0. 0. 1. 2.]
 [0. 0. 2. 3.]]


In [ ]:
a1 = np.array([[1,2],[2,3]])
a2 = np.array([[10,20],[20,30]])
np.block([[a1,np.zeros((2,2))], [np.zeros((2,2,)), a2]])

array([[ 1.,  2.,  0.,  0.],
       [ 2.,  3.,  0.,  0.],
       [ 0.,  0., 10., 20.],
       [ 0.,  0., 20., 30.]])

In [ ]:
for a in soaps[0]:
    print(a)

has_grad_data
ii
pos
grad_covariance_cutoff
covariance_cutoff
data
has_data
grad_data
ci
grad_index_0based
